services:
  database:
    image: "postgres:16.3-alpine3.19"
    environment:
      POSTGRES_PASSWORD: "local_pass"
      POSTGRES_DB: "local_db"
      POSTGRES_USER: "local_user"
    ports:
      - "5432:5432"
