services:
  database:
    container_name: "database_pettech"
    image: "postgres:16.3-alpine3.19"
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
